project: deb-01-371820
dataset: bitcoin
table: bitcoin_pricing
bitcoin_consolidated: combined_BTC_hist_pricing.csv
raw_yahoo: raw_yahoo.csv
stg_data: stg_data.csv
kaggle_data: BTC_4_13_2021.csv
invest_data: Bitcoin Historical Data - Investing.com.csv

OPENAI_API_KEY: 

client_config_backend: settings
client_config:
  client_id: "1038251745050-20f5ebn9ssqufbvt2cl9kfdo5vtb2dvr.apps.googleusercontent.com"
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: client_secrets.json #credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install