project: deb-01-371820
dataset: bitcoin
table: bitcoin_pricing
bitcoin_consolidated: combined_BTC_hist_pricing.csv
raw_yahoo: raw_yahoo.csv
stg_data: stg_data.csv
kaggle_data: BTC_4_13_2021.csv
invest_data: Bitcoin Historical Data - Investing.com.csv